<?xml version="1.0"?>
<robot name="crawler_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.14159265359"/>
  <xacro:property name="BASE_LENGTH" value="0.40"/>
  <xacro:property name="BASE_WIDTH" value="0.30"/>
  <xacro:property name="BASE_HEIGHT" value="0.20"/>
  <xacro:property name="LIDAR_HEIGHT" value="0.10"/>  <xacro:property name="TRACK_RADIUS" value="0.05"/>

  <material name="Black"> <color rgba="0.1 0.1 0.1 1.0"/> </material>
  <material name="Blue"> <color rgba="0.2 0.2 1.0 1.0"/> </material>
  <material name="Red"> <color rgba="1.0 0.1 0.1 1.0"/> </material>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    </link>

  <link name="odom"/>
  <joint name="odom_joint" type="fixed">
    <parent link="odom"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="Blue"/>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${BASE_HEIGHT + 0.05}" rpy="0 0 0"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
      <material name="Red"/>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${BASE_LENGTH/4} 0 ${BASE_HEIGHT + 0.15}" rpy="0 0 0"/>
  </joint>

  <link name="right_track_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0"/>
      <geometry>
        <cylinder radius="${TRACK_RADIUS}" length="${BASE_LENGTH}"/>
      </geometry>
      <material name="Black"/>
    </visual>
  </link>

  <joint name="right_track_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_track_link"/>
    <origin xyz="0 ${-(BASE_WIDTH/2)} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  </robot>
